PHIDGET:
  POT_1_CHANNEL: 1
  POT_2_CHANNEL: 0
  BTS_CHANNEL: 2
  
  POT_1_FREQ_HZ: 50
  POT_2_FREQ_HZ: 50
  BTS_FREQ_HZ: 1000

DXL:
  PROTOCOL_VERSION: 1.0  # RX-24F uses Protocol 1.0
  BAUDRATE: 1000000  # Dynamixel baud rate
  RESOLUTION: 0.065
  TORQUE_ENABLE: 1  # Value for enabling torque
  TORQUE_DISABLE: 0  # Value for disabling torque
  DEVICENAME: "/dev/ttyUSB0"  # TODO
  ADDR_TORQUE_ENABLE: 24
  ADDR_GOAL_POSITION: 30
  ADDR_MOVING_SPEED: 32
  ADDR_TORQUE_LIMIT: 34
  ADDR_PRESENT_POSITION: 36
  ADDR_PRESENT_SPEED: 38
  ADDR_PRESENT_LOAD: 40
  ADDR_PRESENT_INPUT_VOLTAGE: 42
  ADDR_PRESENT_TEMP: 43
  DXL1_ID: 1
  DXL2_ID: 2
  DXL_MOVING_STATUS_THRESHOLD: 10  # Dynamixel moving status threshold
  DXL1_MIN_VALUE: 0
  DXL1_MAX_VALUE: 1023  # actuated magnets at the end of VSA
  DXL2_MIN_VALUE: 0
  DXL2_MAX_VALUE: 500

UR5E:
  ROBOT_ID: "192.168.1.100"

GELSIGHTMINI:
  IMG_WIDTH: 320
  IMG_HEIGHT: 240
  IMG_RGB_CHANNEL: 3

LINEAR_POTENTIOMETER:
  LENGTH_MM: 95
  MAX_OUTPUT_VOLTAGE: 5
  RESOLUTION: 19